Update instructions for version 2021.9
savushkin-r-d/PLCnext-howto pull request #20
Opened 2021-11-02 09:31 UTC by idzm

Fixes #18.

2021-11-08 13:08 UTC, rartem submitted a review, later dismissed

2021-11-11 19:26 UTC, martinboers requested changes
Great work! Only one minor comment:

On line 64 (in section 4), the link to the PLCnext Info Center is broken (sorry!). I think the link should be: 
https://www.plcnext.help/te/Programming/Cpp/Cpp_programming/Working_with_Visual_Studio.htm

2021-11-12 06:46 UTC, martinboers approved these changes

2021-11-12 07:11 UTC, dimabeel approved these changes

2021-11-12 07:11 UTC, merged