some changes
savushkin-r-d/PLCnext-howto pull request #31
Opened 2021-12-13 08:21 UTC by MrSoulfinder

2021-12-22 13:15 UTC, idzm commented
The latest LTS version is `2021.0.5_LTS`, not `2021.0.9_LTS`.

2021-12-22 13:37 UTC, MrSoulfinder reviewed
Change the last version

2021-12-23 06:25 UTC, idzm requested changes

2021-12-23 06:25 UTC, idzm commented on HowTo quick start AXC F 2152 and PLCnext Engineer/readme.md
> +- Download the *.zip firmware file with version **2021.0.5 LTS** at Phoenix Contact [site](https://select.phoenixcontact.com/phoenix/dwl/dwl13a.jsp?fct=dwl&asid=7449344&name=AXC_F_2152_FW2020_0_1_LTS
You also should change link to version `2021.0.5`.

2021-12-23 06:25 UTC, idzm commented on HowTo quick start AXC F 2152 and PLCnext Engineer/readme.md
> +It's important to use the appropriate version of **`"PLCnext Engineer"`** - **`"2021.0.5"`**.  Start **`"PLCnext Engineer"`** and select **`"Empty AXC F 2152 v00 / 2021.0.5 project"`**:
```suggestion
It's important to use the appropriate version of **`"PLCnext Engineer"`** - **`"2021.0.5"`** (or newer).  Start **`"PLCnext Engineer"`** and select **`"Empty AXC F 2152 v00 / 2021.0.5 project"`**:
```

2021-12-23 06:38 UTC, MrSoulfinder reviewed
update link for version 2021.0.5

2021-12-23 07:03 UTC, idzm requested changes

2021-12-23 07:03 UTC, idzm commented on HowTo quick start AXC F 2152 and PLCnext Engineer/readme.md
> +It's important to use the appropriate version of **`"PLCnext Engineer"`** - **`"2021.0.5"`** (or newer).  Start **`"PLCnext Engineer"`** and select **`"Empty AXC F 2152 v00 / 2021.0.5 project"`**:
We only have this option: 
```suggestion
It's important to use the appropriate version of **`"PLCnext Engineer"`** - **`"2021.0.5"`** (or newer).  Start **`"PLCnext Engineer"`** and select **`"Empty AXC F 2152 v00 / 2021.0.0 project"`**:
```

2021-12-23 07:06 UTC, MrSoulfinder commented on HowTo quick start AXC F 2152 and PLCnext Engineer/readme.md
> +It's important to use the appropriate version of **`"PLCnext Engineer"`** - **`"2021.0.5"`** (or newer).  Start **`"PLCnext Engineer"`** and select **`"Empty AXC F 2152 v00 / 2021.0.5 project"`**:
understand, corrected

2021-12-23 07:31 UTC, idzm requested changes
Archive `AXC_F_2152_FW2021_0_5_Bundle.zip` already contains `axcf2152-2021.0.5.35585-LTS.raucb` - so we do not need to run an installer.

2021-12-23 08:01 UTC, MrSoulfinder reviewed
Change the installation steps

2021-12-23 13:22 UTC, idzm approved these changes

2021-12-23 13:23 UTC, merged